# Docker ToolBox (for Windowws)
#
# --- Example: Kouichi Abe 2019/11/28 on Windows10/DockerToolbox. ---
# 1. Virtual machine settings & Start container.
#  1-1. settings -> network -> Port fowarding -> add below.
#           http 80:80
#           mysql 3036:3036
#           phpmyadmin 8087:8087
#  1-2. settings -> share directory -> add project root path.
#  1-3. Exec "Docker quickstart terminal" shortcut.
#        * It is created by Docker toolbox.
#  1-4. Create and start container > docker-compose up -d --build
# 
# 2. Log in to container
#   2-1. > docker exec -it --user=dev_user fukugo-port_php-fpm bash
#       * Before re-exec this, you may have to exec "docker-compose down".
#
# 3. Setup laravel environment.
#   3-1. > cp .env.example .env
#       3-1-1. > modify .env like follows.
#			> DB_HOST=mysql
#			> DB_DATABASE=db_fukugo-port
#			> DB_USERNAME=dev_user
#			> DB_PASSWORD=dev_pass
#   3-2. > composer install
#   3-3. > php artisan key:generate
#
# 4. Run migration and seed > php artisan migrate:fresh --seed
#
# 5. Access to http://127.0.0.1:8086
#     Mail : admin@admin.com
#     Pass : 12345678
#
# 6. (Access to phpMyAdmin is http://127.0.0.1:8087)
# 
version: '3'

services:
    nginx:
        image: nginx:1.17
        container_name: fukugo-port_nginx
        ports:
            - 80:80
        volumes:
            - /fukugo-port:/usr/share/nginx/html
            - /fukugo-port/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - /fukugo-port/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /fukugo-port/docker/nginx/.htpasswd:/etc/nginx/.htpasswd
            - /fukugo-port/docker/nginx/log:/var/log/nginx
        networks:
            my_network:
                ipv4_address: 172.16.238.103

    php-fpm:
        build: ../../php-fpm
        container_name: fukugo-port_php-fpm
        volumes:
            - /fukugo-port:/var/www/html
        networks:
            - my_network
        extra_hosts:
            - "localhost:172.16.238.103"

    mysql:
        image: mysql:5.7
        container_name: fukugo-port_mysql
        environment:
            MYSQL_DATABASE: db_fukugo-port
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: dev_user
            MYSQL_PASSWORD: dev_pass
            TZ: Asia/Tokyo
        ports:
            - 3306:3306
        volumes:
            - fukugo-port-db-data:/var/lib/mysql
        networks:
            - my_network
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
        links:
            - mysql
        ports:
            - 8087:80
        volumes:
            - sessions:/sessions
        networks:
            - my_network

    redis:
        image: redis:3.2.9
        ports:
            - "6379:6379"
        command: redis-server --requirepass foobared
        volumes:
            - redis-data:/data
        networks:
            - my_network

    # on VPN, passwd:secret
    # * latest version is unenable. > https://stackoverflow.com/questions/56459691/undefined-index-element-laravel-dusk
    selenium:
        image: selenium/standalone-chrome-debug:3.141.59-oxygen
        ports:
            - 4444:4444
            - 5900:5900
        depends_on: 
            - nginx
        privileged: true
        networks:
            - my_network

networks:
    my_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
volumes:
    fukugo-port-db-data:
        driver: local
    redis-data:
        driver: local
    sessions:
        driver: local
        
